G/B,G/D#,G/D,G/A#
D/A#,D/E,D/C,D/G#
E/F,E/C#,E/C,E/A#
C/$,C/D#,C/G,C/B
G/B,G/C#,G/A#,G/D
D/G#,D/C#,D/B,D/D#
E/$,E/$,E/C#,E/F
C/B,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/D#,D/A#,D/A
E/E,E/F,E/F,E/D
C/A#,C/A#,C/G,C/B
G/F#,G/C#,G/D,G/D
D/F#,D/D,D/F,D/A
E/E,E/E,E/A#,E/$
C/A#,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/D,D/F,D/A
E/E,E/E,E/B,E/B
C/A#,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/D,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/D,D/F,D/A
E/E,E/E,E/G#,E/B
C/E,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/D,D/F,D/A
E/E,E/E,E/B,E/B
C/F,C/A#,C/G,C/B
G/B,G/C#,G/D,G/C#
D/F#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/B,C/B
G/C,G/C#,G/D,G/D
D/F#,D/A,D/C,D/A
E/G,E/E,E/B,E/B
C/E,C/F,C/A,C/B
G/B,G/C#,G/D,G/D
D/F#,D/A,D/C,D/A
E/E,E/E,E/G#,E/B
C/E,C/A#,C/$,C/B
G/B,G/C#,G/D,G/D
D/F#,D/A,D/C,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/C#,G/D,G/D
D/F#,D/A,D/F,D/B
E/E,E/E,E/B,E/B
C/E,C/A#,C/D#,C/B
G/B,G/C#,G/D,G/D
D/F#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/D,C/F,C/G,C/B
G/B,G/D,G/D,G/A#
D/F#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/F#,C/B
G/B,G/D,G/D,G/D
D/F#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/D,G/D,G/D
D/F#,D/A,D/F,D/A
E/E,E/E,E/F,E/B
C/E,C/A#,C/G,C/B
G/B,G/D,G/D,G/D
D/F#,D/A,D/F,D/A
E/E,E/A#,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/D,G/D,G/D
D/F#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/A
E/E,E/B,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/A
E/A,E/E,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/F#,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/A#,C/G,C/B
G/B,G/D,G/D,G/G
D/A#,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/A
E/E,E/E,E/B,E/B
C/E,C/F,C/$,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/A
E/E,E/E,E/A#,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/A
E/E,E/E,E/B,E/D
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/F
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/B
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D#,G/G
D/D,D/A,D/F,D/D#
E/C#,E/A#,E/B,E/B
C/E,C/F,C/G,C/B
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/G#
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/G#
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/G#
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/A
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/G#
G/A,G/D,G/D,G/G
D/D,D/A,D/C,D/A
E/D,E/$,E/B,E/B
C/E,C/F,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/C#
E/E,E/D,E/B,E/B
C/F,C/A#,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/G,E/B,E/B
C/D#,C/F,C/A,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/G,E/B,E/B
C/E,C/A#,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/E
G/B,G/D,G/D,G/G
D/A,D/A,D/$,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/G,E/B,E/B
C/E,C/A#,C/G,C/E
G/B,G/E,G/D,G/G
D/D,D/$,D/$,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/G,C/E
G/B,G/D,G/F,G/G
D/D,D/A,D/C,D/F#
E/E,E/G,E/B,E/B
C/E,C/F,C/F,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/F#
E/E,E/E,E/A,E/B
C/E,C/A#,C/F,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/E,E/B,E/G
C/E,C/F,C/G,C/E
G/B,G/D,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/A,E/B,E/G
C/E,C/F,C/G,C/C
G/B,G/E,G/D,G/G
D/D,D/A,D/$,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/C
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/F#
E/G#,E/E,E/B,E/B
C/E,C/F,C/D#,C/C
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/F#
E/E,E/A,E/B,E/E
C/E,C/F,C/G,C/C
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/C
G/B,G/D,G/D,G/C#
D/D,D/A,D/F,D/F#
E/E,E/E,E/B,E/B
C/E,C/F,C/G,C/C
G/D,G/D,G/D,G/G
D/D,D/D,D/F,D/F#
E/E,E/E,E/B,E/B
C/E,C/D,C/G,C/C
G/B,G/D,G/D,G/G
D/D,D/A,D/F,D/F#
E/E,E/G,E/B,E/G
C/E,C/F,C/G,C/C
G/B,G/D,G/D,G/G
D/F#,D/A,D/F,D/F#
E/E,E/G,E/B,E/G
C/E,C/F,C/F#,C/C
G/B,G/D,G/B,G/G
D/$,D/A,D/F,D/F#
E/E,E/G,E/B,E/G
C/E,C/D,C/G,C/C
G/B,G/C#,G/D,G/G
D/D,D/A,D/F,D/A
E/E,E/E,E/B,E/B
C/C,C/D,C/G,C/C
G/B,G/D,G/D,G/G
D/D,D/A,D/C,D/A
E/E,E/E,E/B,E/B
C/C,C/D,C/F,C/C
G/B,G/D,G/D,G/A#
D/D,D/A,D/C,D/A
